# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e3a80b30d8859b453c264197ea2a02ba3b53d89de6e6e6398a1e6d550ea603695cd41e4928481aac7516ba900d19c3301e6cadf94c98e344b3870195c12fb14

test:
  secret_key_base: 9d7ef920cf6d590416895d53937aa6dc6915a684670192fa52d459401ab58d429f11f00f3325f90971cd386bce0e7218b65def34fdef8452bf66226c370dcc53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
